In [4]:
import faiss
import numpy as np

# Create a random vector database of 1000 vectors, each of dimension 128
d = 128  # Dimension of vectors
nb = 1000  # Number of vectors
nq = 10  # number of queries
xb = np.random.random((nb, d)).astype('float32')
xq = np.random.random((nq, d)).astype('float32')

# Create a FAISS index
index = faiss.IndexFlatL2(d)  # L2 distance (Euclidean)
index.add(xb)  # Add vectors to the index

print("Index created successfully!")

Index created successfully!


In [5]:
k = 5  # number of nearest neighbors
D, I = index.search(xq, k)

print("Distances:", D)
print("Indices:", I)

Distances: [[14.560784 15.205967 15.295433 15.348925 15.529803]
 [15.383635 15.665143 16.896328 17.007502 17.041325]
 [15.10368  15.296452 15.790037 15.843813 16.021168]
 [14.249252 15.135363 15.288019 15.866387 15.91325 ]
 [14.094816 14.249046 14.519877 14.529622 14.801836]
 [15.009618 15.102521 15.182447 15.460808 15.565136]
 [14.843388 14.998162 15.441964 15.557924 15.563087]
 [16.510515 16.578228 17.10545  17.148117 17.194302]
 [14.771246 14.877812 15.413614 15.467012 15.852699]
 [16.33187  16.573446 17.172298 17.174038 17.432995]]
Indices: [[343 450 282 664 305]
 [993  64 677 893 330]
 [370 242 534 536 184]
 [454 726 114  19 414]
 [134 292 612  27 916]
 [826 666 534 590 279]
 [400 822 245 588 787]
 [990 457 123 939 680]
 [435 856 733 697 353]
 [236 509 144 642 868]]


In [6]:
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

# Initialize a pre-trained sentence transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Example sentences
sentences = ["This is a sentence.", "FAISS is a library for vector search.", "Machine learning is fascinating."]

# Convert sentences to embeddings (vectors)
embeddings = model.encode(sentences)

# Convert embeddings to numpy array of type float32 (required by FAISS)
embeddings = np.array(embeddings).astype('float32')

# Create a FAISS index
d = embeddings.shape[1]  # Embedding dimension
index = faiss.IndexFlatL2(d)  # L2 distance (Euclidean)

# Add the embeddings to the index
index.add(embeddings)

# Query example (for example, the first sentence)
query = model.encode(["FAISS library example"]).astype('float32')

# Search for nearest neighbors (top 3 neighbors)
k = 3
distances, indices = index.search(query, k)

print("Nearest Neighbors (Indices):", indices)
print("Distances:", distances)


/Users/neerajmokha/Documents/ajangid_Github/ml_projects/faiss_env/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


Nearest Neighbors (Indices): [[1 2 0]]
Distances: [[0.9109508 1.7460489 1.8826835]]
